# Generated by Django 4.1.6 on 2023-02-17 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_commentslist_alter_articles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentslist',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Кометарии'},
        ),
        migrations.AddField(
            model_name='commentslist',
            name='news_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.articles'),
            preserve_default=False,
        ),
    ]
