# Generated by Django 4.1.6 on 2023-02-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_commentslist_options_commentslist_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='picture',
            field=models.ImageField(default=123, upload_to='photos'),
            preserve_default=False,
        ),
    ]
